# Generated by Django 3.2.5 on 2021-07-01 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentsDeta',
            new_name='CommentsData',
        ),
    ]
