# Generated by Django 3.2.5 on 2021-07-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20210702_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='timestamp',
        ),
    ]
