# Generated by Django 3.2.5 on 2021-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='comments',
            field=models.TextField(max_length=300),
        ),
    ]
