# Generated by Django 3.2.5 on 2021-07-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20210702_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='id',
            new_name='idno',
        ),
        migrations.RenameField(
            model_name='usercomment',
            old_name='id',
            new_name='idno',
        ),
    ]
