# Generated by Django 3.2.5 on 2021-07-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20210702_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='idno',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usercomment',
            old_name='idno',
            new_name='id',
        ),
    ]
